### ISSUE TITLE
How to set ngxStompConfig url after signing in

### ISSUE THREAD

**Issue by thari119** [kainonly/ngx-message-queue#1]
Hi how can i initialise the stomp config to set the url after i log in for example in the dashboard page. If i set it in app.module i cant get the users token.

Please advice on how to do this?

**Comment by kainonly** [comment]
The project is currently only for testing, and ngx-stomp will be abandoned, you can use  [ng2-stompjs](https://github.com/stomp-js/ng2-stompjs), they have more comprehensive libraries and documentation.
